import = [
	"~/.config/alacritty/themes/nordic.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
dimensions.columns = 200
dimensions.lines = 55
opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 10
