import = [
	"~/.config/alacritty/themes/nordic.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Full"
dimensions.columns = 165
dimensions.lines = 55
opacity = 0.95
blur = true
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 10

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "CopySelection" },
  { key = "V", mods = "Control", action = "PasteSelection" },
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "F", mods = "Control|Shift", action = "ToggleFullScreen" },
]
