#!/bin/bash

BATTERY_LEVEL=$(acpi -b | grep "Battery 0" | grep -E -o '[0-9][0-9]?%')
BATTERY_CHARGE=$(acpi -b | grep "Battery 0" | grep -c "Charging")

if [[ "${BATTERY_CHARGE}" = 1 ]]; then
  echo "󰂄 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 90 ]]; then
  echo "󰂂 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 80 ]]; then
  echo "󰂁 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 70 ]]; then
  echo "󰂀 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 60 ]]; then
  echo "󰁿 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 50 ]]; then
  echo "󰁾 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 40 ]]; then
  echo "󰁽 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 30 ]]; then
  echo "󰁼 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 20 ]]; then
  echo "󰁻 ${BATTERY_LEVEL}"

elif [[ "${BATTERY_CHARGE}" = 0 && "${BATTERY_LEVEL}" = 10 ]]; then
  echo "󰁺 ${BATTERY_LEVEL}"

else 
  echo "󰁹 ${BATTERY_LEVEL}"

fi
